import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { FiDownload, FiArrowLeft, FiAlertTriangle } from 'react-icons/fi';
import DashboardLayout from '../components/Layout/DashboardLayout';
import ScoreCards from '../components/Dashboard/ScoreCards';
import ScoreChart from '../components/Analysis/ScoreChart';
import SkillsSection from '../components/Analysis/SkillsSection';
import SuggestionsSection from '../components/Analysis/SuggestionsSection';
import LoadingSpinner from '../components/Common/LoadingSpinner';
import api from '../services/api';
import toast from 'react-hot-toast';
import './AnalysisPage.css';

const AnalysisPage = () => {
    const { resumeId } = useParams();
    const navigate = useNavigate();
    const [loading, setLoading] = useState(true);
    const [analysis, setAnalysis] = useState(null);
    const [extractedData, setExtractedData] = useState(null);
    const [feedback, setFeedback] = useState(null);

    useEffect(() => {
        loadAnalysis();
    }, [resumeId]);

    const loadAnalysis = async () => {
        try {
            const results = await api.getAnalysisResults(resumeId);
            setAnalysis(results.analysis);
            setExtractedData(results.extracted_data);
            setFeedback(results.feedback);
        } catch (error) {
            console.error('Error loading analysis:', error);
            toast.error('Failed to load analysis results');
            navigate('/dashboard');
        } finally {
            setLoading(false);
        }
    };

    const downloadReport = () => {
        if (!analysis) return;
        const report = `
RESUME INSIGHT REPORT
====================

SCORES:
- Overall Score: ${analysis.resume_score}/100
- ATS Compatibility: ${analysis.ats_compatibility_score}/100
- Skill Match: ${analysis.skill_match_percentage}/100
- Keyword Relevance: ${analysis.keyword_relevance_score}/100

SKILLS IDENTIFIED:
${extractedData?.skills?.split(', ').map(skill => `- ${skill}`).join('\n') || 'No skills found'}

IMPROVEMENT SUGGESTIONS:
${feedback?.improvement_suggestions?.split('; ').map(s => `- ${s}`).join('\n') || 'No suggestions available'}

${feedback?.formatting_suggestions ? `\nFORMATTING SUGGESTIONS:\n${feedback.formatting_suggestions.split('; ').map(s => `- ${s}`).join('\n')}` : ''}

Recommendation Level: ${feedback?.recommendation_level || 'N/A'}

Generated by Resume Insight Tool
        `;

        const blob = new Blob([report], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `resume_analysis_${resumeId}_report.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        toast.success('Report downloaded successfully');
    };

    if (loading) return <LoadingSpinner />;

    const recommendationClass = feedback?.recommendation_level
        ? feedback.recommendation_level.toLowerCase().replace(' ', '-')
        : 'medium-priority';

    return (
        <DashboardLayout>
            <div className="analysis-page-content animate-slide-up">
                {/* Back & Export Row */}
                <div className="analysis-topbar">
                    <button onClick={() => navigate('/dashboard')} className="btn-back">
                        <FiArrowLeft /> Back to Dashboard
                    </button>
                    <button onClick={downloadReport} className="download-btn-main">
                        <FiDownload /> Download Report
                    </button>
                </div>

                {/* Main Header */}
                <div className="analysis-page-header">
                    <h1 className="analysis-title">Resume Analysis Results</h1>
                    <p className="analysis-subtitle">
                        Detailed feedback, key parsing insights, and scoring charts.
                    </p>
                </div>

                {/* Score Cards */}
                {analysis && <ScoreCards scores={analysis} />}
                
                {/* Visual Chart and Skill Metrics Grid */}
                <div className="analysis-visual-grid">
                    <div className="analysis-card radar-card">
                        <h3>Scoring Radar Chart</h3>
                        {analysis && <ScoreChart scores={analysis} />}
                    </div>
                    <div className="analysis-card skills-card">
                        <h3>Extracted Skills</h3>
                        <SkillsSection skills={extractedData?.skills} />
                    </div>
                </div>

                {/* Improvement Recommendations */}
                <div className="analysis-card suggestions-card">
                    <h3>Optimization Suggestions</h3>
                    <SuggestionsSection suggestions={feedback?.improvement_suggestions} />
                </div>
                
                {/* Formatting Suggestions */}
                {feedback?.formatting_suggestions && (
                    <div className="analysis-card formatting-card">
                        <h3>Formatting Suggestions</h3>
                        <p className="formatting-text">{feedback.formatting_suggestions}</p>
                    </div>
                )}

                {/* Final Recommendation Alert */}
                {feedback?.recommendation_level && (
                    <div className={`recommendation-alert priority-${recommendationClass}`}>
                        <FiAlertTriangle className="alert-icon" />
                        <div>
                            <strong>Action Recommendation:</strong>{' '}
                            {feedback.recommendation_level}
                        </div>
                    </div>
                )}
            </div>
        </DashboardLayout>
    );
};

export default AnalysisPage;